### ISSUE TITLE
Name and DoB of patient have to be display in hearder of consultation screen

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#251] opened 2021-07-27 09:09 UTC
## Describe the bug
Lets consider a consultation.
Currently in header it shows "Consultations", but if should display Name and DoB of patient after completing "Registration" step.

## Expected behavior
Should display Name and DoB of patient after completing "Registration" step.

## Screenshots
See Zeplin screenshot:
![dfgdfgdfg](https://user-images.githubusercontent.com/55558015/127128008-83d49553-4c18-4edf-a773-54211c2fbad7.PNG)

**Comment by frescoal** [comment] 2021-07-27 09:15
Duplicate of 230

**Comment by jouz56k** [comment] 2021-07-27 09:21
Okay yes, il me semblait bien, je savais plus où elle était, merci

**Closed** 2021-07-27 09:21 UTC
Labels: bug, duplicate
